server.port=8085
spring.application.name=consumer
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=arkan
spring.rabbitmq.password=12345
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arkanauva.nabil@gmail.com
spring.mail.password=khypiskqvtcszkbc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true