# SERVER
server.port=8080
spring.application.name=auth-service


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT (INI YANG PALING PENTING)
jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=86400000