input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "[@metadata][index_prefix]" => "%{[application]}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservice-%{[application]}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}